CREATE TABLE hr(
id	NVARCHAR(200) UNIQUE,
first_name	NVARCHAR(200) NOT NULL,
last_name	NVARCHAR(200) NOT NULL,
birthdate	NVARCHAR(200) NOT NULL,
gender	NVARCHAR(200)NOT NULL,
race	NVARCHAR(200)NOT NULL,
department	NVARCHAR(200) NOT NULL,
jobtitle	NVARCHAR(200) NOT NULL,
location	NVARCHAR(200) NOT NULL,
hire_date	NVARCHAR(200) NOT NULL,
termdate	NVARCHAR(200) NOT NULL,
location_city	NVARCHAR(200) NOT NULL,
location_state NVARCHAR(200) NOT NULL
)
